[package]
name = "Terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
color-eyre = "0.6"
serde = { version = "1.0.228", features = ["derive"] }